# 1.温度数据分析
## 某城市一周的最高气温为 [28, 30, 29, 31, 32, 30,29]
### 计算平均气温、最高气温和最低气温
### 找出气温超过30℃的天数

In [3]:
import numpy as np
from numpy.ma.extras import vstack

temps = np.array([28, 30, 29, 31, 32, 30, 29])
print(temps)
print("平均气温：", np.mean(temps))
print("最高气温：", np.max(temps))
print("最低气温", np.min(temps))
print("超过30°C的天数：", len(temps[temps > 30]))

[28 30 29 31 32 30 29]
平均气温： 29.857142857142858
最高气温： 32
最低气温 28
超过30°C的天数： 2


# 题目 2：学生成绩统计
## 题目：某班级 5 名学生的数学成绩为 [85, 90, 78, 92, 88]。
### •	计算成绩的平均分、中位数和标准差。
### •	将成绩转换为百分制（假设满分为 100）。


In [4]:
scores = np.array([85, 90, 78, 92, 88])
print("平均分：", np.mean(scores))
print("中位数", np.median(scores))
print("标准差：", np.std(scores))

平均分： 86.6
中位数 88.0
标准差： 4.882622246293481


# 题目 3：矩阵运算
## 题目：给定矩阵 A = [[1, 2], [3, 4]] 和 B = [[5, 6], [7, 8]]。
### •	计算 A + B 和 A * B（逐元素乘法）。
### •	计算 A 和 B 的矩阵乘法（点积）。


In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A + B\n", A + B)
print("A * B\n", A * B)
print("A @ B\n", A @ B)

A + B
 [[ 6  8]
 [10 12]]
A * B
 [[ 5 12]
 [21 32]]
A @ B
 [[19 22]
 [43 50]]


# 题目 4：随机数据生成
## 题目：生成一个 (3, 4) 的随机整数数组，范围 [0, 10)。
### •	计算每列的最大值和每行的最小值。
### •	将数组中的所有奇数替换为 -1。


In [10]:
arr = np.random.randint(0, 10, (3, 4))
print("arr\n", arr)
print("每列最大值：", np.max(arr, axis=0))
print("每行最小值", np.min(arr, axis=1))
arr[arr % 2 == 1] = -1
print(arr)

arr
 [[1 8 1 9]
 [8 9 8 7]
 [5 7 3 8]]
每列最大值： [8 9 8 9]
每行最小值 [1 7 3]
[[-1  8 -1 -1]
 [ 8 -1  8 -1]
 [-1 -1 -1  8]]


# 题目 5：数组变形
## 题目：创建一个 1 到 12 的一维数组，并转换为 (3, 4) 的二维数组。
### •	计算每行的和与每列的平均值。
### •	将数组展平为一维数组。


In [11]:
arr = np.arange(1, 13).reshape((3, 4))
print("每行的和：", np.sum(arr, axis=0))
print("每列的平均值：", np.mean(arr, axis=1))
print("展平后：", arr.flatten())

每行的和： [15 18 21 24]
每列的平均值： [ 2.5  6.5 10.5]
展平后： [ 1  2  3  4  5  6  7  8  9 10 11 12]


# 题目 6：布尔索引
## 题目：生成一个 (5, 5) 的随机数组，范围 [0, 20)。
### •	找出数组中大于 10 的元素。
### •	将所有大于 10 的元素替换为 0。


In [14]:
arr = np.random.randint(0, 20, (5, 5))
print(arr)
print("大于5的数：", arr[arr > 10])
arr[arr > 10] = 0
print("替换后：\n", arr)

[[19  3 16 18 18]
 [11 14 11  7  7]
 [ 1 12  2  9 16]
 [11  0  3 15  9]
 [14 10  8  6 15]]
大于5的数： [19 16 18 18 11 14 11 12 16 11 15 14 15]
替换后：
 [[ 0  3  0  0  0]
 [ 0  0  0  7  7]
 [ 1  0  2  9  0]
 [ 0  0  3  0  9]
 [ 0 10  8  6  0]]


# 题目 7：统计函数应用
## 题目：某公司 6 个月的销售额（万元）为 [120, 135, 110, 125, 130, 140]。
### •	计算销售额的总和、均值和方差。
### •	找出销售额最高的月份和最低的月份。


In [16]:
sales = np.array([120, 135, 110, 125, 130, 140])
print("总和：", np.sum(sales))
print("均值：", np.mean(sales))
print("方差：",np.var(sales))
print("最高月份：", np.argmax(sales) + 1)
print("最低月份：", np.argmin(sales) + 1)

总和： 760
均值： 126.66666666666667
方差： 97.22222222222223
最高月份： 6
最低月份： 3


# 题目 8：数组拼接
## 题目：给定 A = [1, 2, 3] 和 B = [4, 5, 6]。
### •	水平拼接为 [1, 2, 3, 4, 5, 6]。
### •	垂直拼接为 [[1, 2, 3], [4, 5, 6]]。


In [23]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print("水平拼接：", np.concatenate((A, B)))
print("垂直拼接：\n", np.vstack((A, B)))

水平拼接： [1 2 3 4 5 6]
垂直拼接：
 [[1 2 3]
 [4 5 6]]


# 题目 9：唯一值与排序
## 题目：给定数组 [2, 1, 2, 3, 1, 4, 3]。
### •	找出唯一值并排序。
### •	计算每个唯一值出现的次数。


In [24]:
arr = np.array([2, 1, 2, 3, 1, 4, 3])
unique_values, counts = np.unique(arr, return_counts=True)
print("唯一值：", unique_values)
print("出现次数：", counts)

<UNK> [1 2 3 4]
<UNK> [2 2 2 1]


# 题目 10：缺失值处理
## 题目：给定数组 [1, np.nan, 3, np.nan, 5]。
### •	计算非缺失值的数量。
### •	将缺失值替换为 0


In [27]:
arr = np.array([1, np.nan, 3, np.nan, 5])
print(arr)
print("非缺失值数量：", np.sum(~np.isnan(arr)))
arr[np.isnan(arr)] = 0
print(arr)

[ 1. nan  3. nan  5.]
非缺失值数量： 3
[1. 0. 3. 0. 5.]
